import type { Solicitud, CuentaAnalitica, Organismo, Expediente, Convenio, Mail, UsuarioInterno } from '@/types'

export const CUENTAS_ANALITICAS: CuentaAnalitica[] = [
  { id: '1', codigo: 'INTA-2025-001', nombre: 'Mejoramiento genético bovino', organismo: 'INTA', saldo_total: 12500000, saldo_disponible: 8340000, moneda: 'ARS' },
  { id: '2', codigo: 'INTA-2025-002', nombre: 'Sustentabilidad agroecológica Pampa', organismo: 'INTA', saldo_total: 9800000, saldo_disponible: 5200000, moneda: 'ARS' },
  { id: '3', codigo: 'SENASA-2025-001', nombre: 'Control sanitario fronteras', organismo: 'SENASA', saldo_total: 7600000, saldo_disponible: 6100000, moneda: 'ARS' },
  { id: '4', codigo: 'INA-2025-001', nombre: 'Monitoreo cuencas hídricas NOA', organismo: 'INA', saldo_total: 4200000, saldo_disponible: 1900000, moneda: 'ARS' },
  { id: '5', codigo: 'INTL-2025-001', nombre: 'Cooperación técnica IICA 2025', organismo: 'IICA', saldo_total: 85000, saldo_disponible: 62000, moneda: 'USD' },
  { id: '6', codigo: 'INTL-2025-002', nombre: 'Proyecto BID Agro-Climático', organismo: 'BID', saldo_total: 150000, saldo_disponible: 98000, moneda: 'USD' },
]

export const ORGANISMOS: Organismo[] = [
  { id: '1', nombre: 'INTA',   codigo: 'INTA',   tipo: 'nacional',       referente: 'Martín Fernández', email: 'mfernandez@inta.gob.ar' },
  { id: '2', nombre: 'SENASA', codigo: 'SENASA', tipo: 'nacional',       referente: 'Laura Gómez',      email: 'lgomez@senasa.gob.ar' },
  { id: '3', nombre: 'INA',    codigo: 'INA',    tipo: 'nacional',       referente: 'Carlos Ríos',      email: 'crios@ina.gob.ar' },
  { id: '4', nombre: 'IICA',   codigo: 'IICA',   tipo: 'internacional',  referente: 'Ana Soto',         email: 'asoto@iica.int' },
  { id: '5', nombre: 'BID',    codigo: 'BID',    tipo: 'internacional',  referente: 'Pierre Moreau',    email: 'pmoreau@iadb.org' },
]

export const SOLICITUDES: Solicitud[] = [
  {
    id: '1', nro: 'EXP-2026-0047', tipo: 'pago_factura', bandeja: 'nacional',
    estado: 'en_tesoreria', concepto: 'Análisis de suelos laboratorio regional Córdoba',
    importe: 148500, moneda: 'ARS', organismo: 'INTA', cuenta_analitica: 'INTA-2025-002',
    beneficiario: 'LabSuelos S.A.', solicitante: 'Ing. Pedro Blanco', responsable_area: 'René Castro',
    fecha_solicitud: '2026-05-08', fecha_actualizacion: '2026-05-09', odoo_id: 1084, expediente_id: 'exp-1',
    historial: [
      { id: 'h1', fecha: '2026-05-08 09:14', usuario: 'Pedro Blanco', area: 'INTA', accion: 'Solicitud creada', nota: 'Factura adjunta' },
      { id: 'h2', fecha: '2026-05-08 10:30', usuario: 'René Castro', area: 'Administración', accion: 'Recibido en mesa de entrada', nota: 'Derivado a administración' },
      { id: 'h3', fecha: '2026-05-09 08:45', usuario: 'René Castro', area: 'Administración', accion: 'Expediente iniciado — FA-2026-00124', nota: 'Factura registrada en Odoo #1084' },
      { id: 'h4', fecha: '2026-05-09 11:20', usuario: 'Sistema', area: 'Administración', accion: 'Derivado a Tesorería', nota: 'Asignado a Ramiro Flores' },
    ],
  },
  {
    id: '2', nro: 'EXP-2026-0046', tipo: 'anticipo', bandeja: 'nacional',
    estado: 'en_gestion', concepto: 'Anticipo viaje técnico jornadas fitosanitarias Mendoza',
    importe: 85000, moneda: 'ARS', organismo: 'SENASA', cuenta_analitica: 'SENASA-2025-001',
    beneficiario: 'Laura Gómez', solicitante: 'Laura Gómez', responsable_area: 'René Castro',
    fecha_solicitud: '2026-05-07', fecha_actualizacion: '2026-05-08', expediente_id: 'exp-2',
    historial: [
      { id: 'h1', fecha: '2026-05-07 14:00', usuario: 'Laura Gómez', area: 'SENASA', accion: 'Solicitud creada' },
      { id: 'h2', fecha: '2026-05-08 09:00', usuario: 'René Castro', area: 'Administración', accion: 'Recibido en mesa de entrada' },
      { id: 'h3', fecha: '2026-05-08 11:00', usuario: 'René Castro', area: 'Administración', accion: 'En revisión — solicitando documentación adicional', nota: 'Falta nota de autorización' },
    ],
  },
  {
    id: '3', nro: 'EXP-2026-0045', tipo: 'contrato', bandeja: 'nacional',
    estado: 'pendiente', concepto: 'Contrato consultoría especialista suelos Alejandro Vera',
    importe: 320000, moneda: 'ARS', organismo: 'INTA', cuenta_analitica: 'INTA-2025-001',
    beneficiario: 'Alejandro Vera', solicitante: 'Ing. Sofía Mendez', responsable_area: 'René Castro',
    fecha_solicitud: '2026-05-06', fecha_actualizacion: '2026-05-06',
    historial: [
      { id: 'h1', fecha: '2026-05-06 10:30', usuario: 'Sofía Mendez', area: 'INTA', accion: 'Solicitud creada', nota: 'Contrato a 3 meses, modalidad RRHH' },
      { id: 'h2', fecha: '2026-05-06 13:00', usuario: 'René Castro', area: 'Administración', accion: 'Recibido en mesa de entrada' },
    ],
  },
  {
    id: '4', nro: 'EXP-2026-0044', tipo: 'rendicion', bandeja: 'nacional',
    estado: 'pagado', concepto: 'Rendición anticipo jornada técnica San Juan marzo 2026',
    importe: 62400, moneda: 'ARS', organismo: 'INA', cuenta_analitica: 'INA-2025-001',
    beneficiario: 'Carlos Ríos', solicitante: 'Carlos Ríos', responsable_area: 'René Castro',
    fecha_solicitud: '2026-04-20', fecha_actualizacion: '2026-05-02', odoo_id: 1071, expediente_id: 'exp-4',
    historial: [
      { id: 'h1', fecha: '2026-04-20 09:00', usuario: 'Carlos Ríos', area: 'INA', accion: 'Rendición presentada' },
      { id: 'h2', fecha: '2026-04-21 10:00', usuario: 'René Castro', area: 'Administración', accion: 'Documentación verificada' },
      { id: 'h3', fecha: '2026-04-22 14:30', usuario: 'René Castro', area: 'Administración', accion: 'Cargado en Odoo', nota: 'Odoo #1071' },
      { id: 'h4', fecha: '2026-04-23 11:00', usuario: 'Ramiro Flores', area: 'Tesorería', accion: 'Pago procesado' },
      { id: 'h5', fecha: '2026-05-02 09:00', usuario: 'Sistema', area: 'Sistema', accion: 'Conciliación confirmada — expediente cerrado' },
    ],
  },
  {
    id: '5', nro: 'EXP-2026-0043', tipo: 'solicitud_compra', bandeja: 'nacional',
    estado: 'rechazado', concepto: 'Compra reactivos laboratorio CABA — sin proveedor homologado',
    importe: 95000, moneda: 'ARS', organismo: 'SENASA', cuenta_analitica: 'SENASA-2025-001',
    beneficiario: 'LabReactivos del Norte SRL', solicitante: 'Lucas Pereyra',
    fecha_solicitud: '2026-04-18', fecha_actualizacion: '2026-04-19',
    historial: [
      { id: 'h1', fecha: '2026-04-18 16:00', usuario: 'Lucas Pereyra', area: 'SENASA', accion: 'Solicitud creada' },
      { id: 'h2', fecha: '2026-04-19 09:30', usuario: 'René Castro', area: 'Administración', accion: 'Rechazado — proveedor no homologado', nota: 'Debe tramitar alta de proveedor primero' },
    ],
  },
  {
    id: '6', nro: 'EXP-2026-I-012', tipo: 'pago_factura', bandeja: 'internacional',
    estado: 'en_gestion', concepto: 'Honorarios consultor IICA — Tiago Méndez — abril 2026',
    importe: 4500, moneda: 'USD', organismo: 'IICA', cuenta_analitica: 'INTL-2025-001',
    beneficiario: 'Tiago Méndez', solicitante: 'Ana Soto', responsable_area: 'Cata Ramírez',
    fecha_solicitud: '2026-05-05', fecha_actualizacion: '2026-05-07', expediente_id: 'exp-6',
    historial: [
      { id: 'h1', fecha: '2026-05-05 11:00', usuario: 'Ana Soto', area: 'IICA', accion: 'Solicitud creada', nota: 'Factura en USD adjunta' },
      { id: 'h2', fecha: '2026-05-06 09:30', usuario: 'Cata Ramírez', area: 'Internacional', accion: 'Control previo iniciado', nota: 'Verificando gastos permitidos por proyecto' },
      { id: 'h3', fecha: '2026-05-07 10:00', usuario: 'Cata Ramírez', area: 'Internacional', accion: 'Control aprobado — derivado a administración' },
    ],
  },
  {
    id: '7', nro: 'EXP-2026-I-011', tipo: 'anticipo', bandeja: 'internacional',
    estado: 'pendiente', concepto: 'Anticipo pasajes y viáticos reunión BID — Washington DC — junio 2026',
    importe: 3200, moneda: 'USD', organismo: 'BID', cuenta_analitica: 'INTL-2025-002',
    beneficiario: 'Ernesto Villarreal', solicitante: 'Pierre Moreau', responsable_area: 'Cata Ramírez',
    fecha_solicitud: '2026-05-09', fecha_actualizacion: '2026-05-09',
    historial: [
      { id: 'h1', fecha: '2026-05-09 14:00', usuario: 'Pierre Moreau', area: 'BID', accion: 'Solicitud creada', nota: 'Reunión técnica 15-17 junio 2026' },
    ],
  },
  {
    id: '8', nro: 'EXP-2026-I-010', tipo: 'reintegro', bandeja: 'internacional',
    estado: 'pagado', concepto: 'Reintegro gastos misión técnica IICA — Buenos Aires — marzo 2026',
    importe: 1800, moneda: 'USD', organismo: 'IICA', cuenta_analitica: 'INTL-2025-001',
    beneficiario: 'Ana Soto', solicitante: 'Ana Soto', responsable_area: 'Cata Ramírez',
    fecha_solicitud: '2026-04-10', fecha_actualizacion: '2026-04-28', odoo_id: 1065, expediente_id: 'exp-8',
    historial: [
      { id: 'h1', fecha: '2026-04-10 09:00', usuario: 'Ana Soto', area: 'IICA', accion: 'Reintegro presentado' },
      { id: 'h2', fecha: '2026-04-11 10:00', usuario: 'Cata Ramírez', area: 'Internacional', accion: 'Control previo completado' },
      { id: 'h3', fecha: '2026-04-14 09:00', usuario: 'René Castro', area: 'Administración', accion: 'Cargado en Odoo', nota: 'Odoo #1065' },
      { id: 'h4', fecha: '2026-04-28 15:00', usuario: 'Sistema', area: 'Sistema', accion: 'Pago conciliado — expediente cerrado' },
    ],
  },
]

export const CONVENIOS: Convenio[] = [
  { id: 'c1', codigo: 'CONV-INTA-2025-001', nombre: 'Mejoramiento genético bovino', organismo: 'INTA', estado: 'vigente', inicio: '2025-01-01', vencimiento: '2025-12-31', monto: 12500000, moneda: 'ARS' },
  { id: 'c2', codigo: 'CONV-INTA-2025-002', nombre: 'Sustentabilidad agroecológica Pampa', organismo: 'INTA', estado: 'vigente', inicio: '2025-03-01', vencimiento: '2026-02-28', monto: 9800000, moneda: 'ARS' },
  { id: 'c3', codigo: 'CONV-INTA-2024-003', nombre: 'Programa semillas resistentes NOA', organismo: 'INTA', estado: 'vencido', inicio: '2024-01-01', vencimiento: '2024-12-31', monto: 5400000, moneda: 'ARS' },
  { id: 'c4', codigo: 'CONV-SENASA-2025-001', nombre: 'Control sanitario fronteras norte', organismo: 'SENASA', estado: 'vigente', inicio: '2025-02-01', vencimiento: '2025-12-31', monto: 7600000, moneda: 'ARS' },
  { id: 'c5', codigo: 'CONV-INA-2025-001', nombre: 'Monitoreo cuencas hídricas NOA', organismo: 'INA', estado: 'vigente', inicio: '2025-04-01', vencimiento: '2026-03-31', monto: 4200000, moneda: 'ARS' },
  { id: 'c6', codigo: 'CONV-IICA-2025-001', nombre: 'Cooperación técnica IICA 2025', organismo: 'IICA', estado: 'vigente', inicio: '2025-01-01', vencimiento: '2025-12-31', monto: 85000, moneda: 'USD' },
]

export const MAILS_INTA: Mail[] = [
  { id: 'm1', asunto: 'Solicitud EXP-2026-0047 aprobada y en tesorería', de: 'Argeninta', fecha: '2026-05-09', leido: false, preview: 'Su solicitud de pago de factura fue aprobada y derivada a tesorería para procesamiento.' },
  { id: 'm2', asunto: 'Documentación faltante — EXP-2026-0046', de: 'Argeninta', fecha: '2026-05-08', leido: true, preview: 'Para continuar con el trámite, por favor adjunte la nota de autorización del referente técnico.' },
  { id: 'm3', asunto: 'Nuevo convenio disponible para revisión', de: 'Argeninta', fecha: '2026-05-05', leido: true, preview: 'El convenio CONV-INTA-2025-002 fue renovado y está disponible para su revisión.' },
  { id: 'm4', asunto: 'Pago procesado — EXP-2026-0044', de: 'Argeninta', fecha: '2026-05-02', leido: true, preview: 'Se confirmó el pago de la rendición de anticipo correspondiente a la jornada técnica en San Juan.' },
]

export const MAILS_INTERNO: Mail[] = [
  { id: 'mi1', asunto: 'EXP-2026-0046 requiere documentación adicional', de: 'INTA', organismo: 'INTA', fecha: '2026-05-09', leido: false, preview: 'El organismo solicita aclaración sobre la nota de autorización para el anticipo de viáticos.' },
  { id: 'mi2', asunto: 'Aprobación pendiente — FAC-003 SENASA', de: 'SENASA', organismo: 'SENASA', fecha: '2026-05-08', leido: false, preview: 'La factura FAC-003 requiere revisión y aprobación antes del cierre de semana.' },
  { id: 'mi3', asunto: 'Convenio IICA-2025 listo para firmar', de: 'IICA', organismo: 'IICA', fecha: '2026-05-07', leido: true, preview: 'Se completaron las instancias previas. El convenio está listo para firma digital.' },
  { id: 'mi4', asunto: 'Nueva solicitud de compra — INA', de: 'INA', organismo: 'INA', fecha: '2026-05-06', leido: true, preview: 'INA presenta solicitud de compra de insumos para el laboratorio de cuencas hídricas NOA.' },
]

export const USUARIOS_INTERNOS: UsuarioInterno[] = [
  { id: 'u1', nombre: 'Carlos López', area: 'Finanzas', tareasActivas: 3, completadasHoy: 1 },
  { id: 'u2', nombre: 'Lucía Fernández', area: 'Administración', tareasActivas: 2, completadasHoy: 3 },
  { id: 'u3', nombre: 'Pedro Sánchez', area: 'Tesorería', tareasActivas: 0, completadasHoy: 0 },
  { id: 'u4', nombre: 'Cata Ramírez', area: 'Internacional', tareasActivas: 1, completadasHoy: 2 },
]

/** Expedientes digitales — equivalente al sistema ESIGA */
export const EXPEDIENTES: Expediente[] = [
  {
    id: 'exp-1',
    codigo_fa: 'FA-2026-00124',
    fecha_solicitud: '2026-05-08',
    estado: 'en_tramitacion',
    solicitante: 'Ing. Pedro Blanco',
    subtitulo_organico: 'INTA — Dirección Nacional de Investigación',
    usuario_titular: 'René Castro',
    tipo_tramite: 'Pago de factura a proveedor externo',
    quien_provee: 'LabSuelos S.A.',
    importe_comprobante: 148500,
    moneda: 'ARS',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'Ramiro Flores',
    fecha_ultima_modificacion: '2026-05-09',
    motivo_modificacion: 'Derivado a Tesorería para procesamiento de pago',
    solicitud_id: '1',
    odoo_id: 1084,
  },
  {
    id: 'exp-2',
    codigo_fa: 'FA-2026-00123',
    fecha_solicitud: '2026-05-07',
    estado: 'en_tramitacion',
    solicitante: 'Laura Gómez',
    subtitulo_organico: 'SENASA — Coordinación de Sanidad Animal',
    usuario_titular: 'René Castro',
    tipo_tramite: 'Anticipo de fondos para viaje oficial',
    quien_provee: 'N/A — beneficiario directo',
    importe_comprobante: 85000,
    moneda: 'ARS',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'René Castro',
    fecha_ultima_modificacion: '2026-05-08',
    motivo_modificacion: 'Pendiente nota de autorización del referente',
    solicitud_id: '2',
  },
  {
    id: 'exp-3',
    codigo_fa: 'FA-2026-00119',
    fecha_solicitud: '2026-04-28',
    estado: 'en_tramitacion',
    solicitante: 'Dra. Valentina Cruz',
    subtitulo_organico: 'INTA — Estación Experimental Balcarce',
    usuario_titular: 'René Castro',
    tipo_tramite: 'Pago de factura a proveedor externo',
    quien_provee: 'Agroquímicos del Sur S.R.L.',
    importe_comprobante: 287000,
    moneda: 'ARS',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'René Castro',
    fecha_ultima_modificacion: '2026-04-30',
    motivo_modificacion: 'Verificación de conformidad con convenio INTA-2025-001',
  },
  {
    id: 'exp-4',
    codigo_fa: 'FA-2026-00108',
    fecha_solicitud: '2026-04-20',
    estado: 'completado',
    solicitante: 'Carlos Ríos',
    subtitulo_organico: 'INA — División Hidrología',
    usuario_titular: 'René Castro',
    tipo_tramite: 'Rendición de anticipo de fondos',
    quien_provee: 'N/A — rendición de cuentas',
    importe_comprobante: 62400,
    moneda: 'ARS',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'Sistema',
    fecha_ultima_modificacion: '2026-05-02',
    motivo_modificacion: 'Conciliación bancaria confirmada. Expediente cerrado.',
    solicitud_id: '4',
    odoo_id: 1071,
  },
  {
    id: 'exp-5',
    codigo_fa: 'FA-2026-00097',
    fecha_solicitud: '2026-04-05',
    estado: 'completado',
    solicitante: 'Ing. Marcos Ibáñez',
    subtitulo_organico: 'SENASA — Laboratorio Central',
    usuario_titular: 'René Castro',
    tipo_tramite: 'Solicitud de compra de equipamiento',
    quien_provee: 'TecnoLab Argentina S.A.',
    importe_comprobante: 540000,
    moneda: 'ARS',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'Sistema',
    fecha_ultima_modificacion: '2026-04-25',
    motivo_modificacion: 'Pago procesado y conciliado. Bien entregado con conformidad.',
    odoo_id: 1058,
  },
  {
    id: 'exp-6',
    codigo_fa: 'FA-2026-I-018',
    fecha_solicitud: '2026-05-05',
    estado: 'en_tramitacion',
    solicitante: 'Ana Soto',
    subtitulo_organico: 'IICA — Representación Argentina',
    usuario_titular: 'Cata Ramírez',
    tipo_tramite: 'Pago de honorarios — consultor internacional',
    quien_provee: 'Tiago Méndez (consultor independiente)',
    importe_comprobante: 4500,
    moneda: 'USD',
    caracter: 'Reservado',
    usuario_ultima_modificacion: 'Cata Ramírez',
    fecha_ultima_modificacion: '2026-05-07',
    motivo_modificacion: 'Control previo aprobado. Pendiente aprobación de divisas.',
    solicitud_id: '6',
  },
  {
    id: 'exp-7',
    codigo_fa: 'FA-2026-I-015',
    fecha_solicitud: '2026-04-10',
    estado: 'completado',
    solicitante: 'Ana Soto',
    subtitulo_organico: 'IICA — Representación Argentina',
    usuario_titular: 'Cata Ramírez',
    tipo_tramite: 'Reintegro de gastos misión oficial',
    quien_provee: 'N/A — beneficiario directo',
    importe_comprobante: 1800,
    moneda: 'USD',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'Sistema',
    fecha_ultima_modificacion: '2026-04-28',
    motivo_modificacion: 'Conciliación confirmada. Expediente cerrado.',
    solicitud_id: '8',
    odoo_id: 1065,
  },
  {
    id: 'exp-8',
    codigo_fa: 'FA-2026-00082',
    fecha_solicitud: '2026-03-18',
    estado: 'anulado',
    solicitante: 'Roberto Salas',
    subtitulo_organico: 'INTA — Programa Nacional Trigo',
    usuario_titular: 'René Castro',
    tipo_tramite: 'Pago de factura a proveedor externo',
    quien_provee: 'Semillas del NOA S.A.',
    importe_comprobante: 176000,
    moneda: 'ARS',
    caracter: 'Ordinario',
    usuario_ultima_modificacion: 'René Castro',
    fecha_ultima_modificacion: '2026-03-25',
    motivo_modificacion: 'Anulado por error en cuenta analítica. El solicitante debe reiniciar el trámite.',
  },
]
